// ============================================================
//  products.js — Base de datos de productos de Tienda Mix
//
//  ── CÓMO AGREGAR O EDITAR PRODUCTOS ────────────────────────
//  Cada producto tiene los siguientes campos:
//    id       → número único (no repetir)
//    name     → nombre que se muestra en la tienda
//    cat      → categoría: "esencias" | "bases" | "bubbas" | "desechables" | "utensilios"
//    image    → ruta de la imagen (carpeta assets/productos/)
//    emoji    → emoji de respaldo si la imagen no carga
//    price    → precio en MXN (número)
//    badge    → "new" | "hot" | "sale" | null
//    stock    → cantidad disponible (0 = agotado)
//    flavors  → sabores o presentaciones (texto)
//    desc     → descripción larga del producto
//    tags     → etiquetas cortas (arreglo de strings)
//
//  ── CÓMO PONER TUS IMÁGENES ────────────────────────────────
//  1. Guarda la foto en:  assets/productos/
//  2. Escribe la ruta exacta en el campo "image"
//  3. Formato recomendado: .webp o .png   Tamaño ideal: 600×600 px
//  Si la imagen no existe, se muestra el emoji automáticamente.
// ============================================================

const PRODUCTS = [
  // ─── ESENCIAS & SIROPES ───────────────────────────────────
  {
    id: 1,
    name: "Esencias Verona Frutal",
    cat: "esencias",
    image: "assets/productos/verona-frutales.png",
    emoji: "🍓",
    price: 155,
    badge: "hot",
    stock: 30,
    flavors: "Chicle · Blueberry · Maracuyá · Mojito · Rompope · Vainilla · Natural · Cereza · Kiwi",
    desc: "Jarabe saborizante Verona línea Frutal. Ideal para bebidas frías, cafés y cocteles. Presentación 1 litro.",
    tags: ["1 Litro", "Línea Frutal", "Verona"],
  },
  {
    id: 2,
    name: "Esencias Verona Neón",
    cat: "esencias",
    image: "assets/productos/verona-neon.png",
    emoji: "💜",
    price: 160,
    badge: "new",
    stock: 20,
    flavors: "Mora Azul · Manzana Verde · Algodón de Azúcar · Citrus",
    desc: "Siropes Verona línea Neón con colores vibrantes que brillan bajo luz UV. Perfectos para bebidas llamativas.",
    tags: ["1 Litro", "Línea Neón", "UV Glow"],
  },
  {
    id: 3,
    name: "Verona Glitter",
    cat: "esencias",
    image: "assets/productos/verona-glitter.png",
    emoji: "✨",
    price: 160,
    badge: "new",
    stock: 15,
    flavors: "Uva · Blueberry · Mora Azul",
    desc: "Sirope con partículas glitter comestibles que dan un efecto espectacular a tus bebidas y cocteles.",
    tags: ["1 Litro", "Glitter", "Verona"],
  },
  {
    id: 4,
    name: "Torino Sirope Glitter (Frutales)",
    cat: "esencias",
    image: "assets/productos/torinosiropefresa.png",
    emoji: "🫐",
    price: 145,
    badge: null,
    stock: 25,
    flavors: "Fresa · Mango · Mora · Caramelo · Moka · Crema Irlandesa · Curazao · Manzana Verde · Violeta · Frutos Rojos",
    flavorImages: {
      "Fresa":          "assets/productos/torinosiropefresa.png",
      "Mango":          "assets/productos/torinosiropemango.png",
      "Mora":           "assets/productos/torinosiropemora.png",
      "Caramelo":       "assets/productos/torinosiropecaramelo.png",
      "Moka":           "assets/productos/torinosiropemoka.png",
      "Crema Irlandesa":"assets/productos/torinosiropecremairlandesa.png",
      "Curazao":        "assets/productos/torino-curazao.png",
      "Manzana Verde":  "assets/productos/torino-manzana-verde.png",
      "Violeta":        "assets/productos/torino-violeta.png",
      "Frutos Rojos":   "assets/productos/torino-frutos-rojos.png",
    },
    desc: "Siropes Torino de alta concentración para frappés, sodas italianas y cocteles gourmet.",
    tags: ["1 Litro", "Torino", "Gourmet"],
  },
  {
    id: 6,
    name: "Esencia para Micheladas",
    cat: "esencias",
    image: "assets/productos/esencia-micheladas.webp",
    emoji: "🍺",
    price: 48,
    badge: null,
    stock: 40,
    flavors: "Clásica · Mango · Tamarindo · Gourmet · Mora Azul · Fresa · Mango Habanero",
    desc: "Esencia concentrada para micheladas. Desde 500ml hasta 21 litros para mayoreo.",
    tags: ["500ml desde $48", "Varios litros", "Micheladas"],
  },

  // ─── BASES EN POLVO ──────────────────────────────────────
  {
    id: 7,
    name: "Bases en Polvo Clásicas",
    cat: "bases",
    image: "assets/productos/bases-polvo-clasicas.webp",
    emoji: "☕",
    price: 300,
    badge: "hot",
    stock: 22,
    flavors: "Capuccino · Taro · Fresas c/Crema · Cookies & Cream · Caramel · Moka · Chocolate Blanco · Vainilla · Cajeta",
    desc: "Bases en polvo para preparar frappés, lattes y cafés calientes. Alta calidad, sabor intenso.",
    tags: ["Frappé", "Latte", "Café caliente"],
  },
  {
    id: 8,
    name: "Bases Gourmet en Polvo",
    cat: "bases",
    image: "assets/productos/bases-polvo-gourmet.webp",
    emoji: "🍵",
    price: 390,
    badge: "new",
    stock: 14,
    flavors: "Matcha · Yoghurt · Dragón Fruit · Red Velvet · Té Chai · ChocoAvellana",
    desc: "Línea gourmet para bebidas premium. Sabores únicos y tendencia para cafeterías modernas.",
    tags: ["Gourmet", "Frappé", "Latte"],
  },
  {
    id: 9,
    name: "Base Neutra Crystal",
    cat: "bases",
    image: "assets/productos/base-crystal.webp",
    emoji: "💎",
    price: 290,
    badge: "new",
    stock: 10,
    flavors: "Sabor neutro base agua — rinde 22 frappés de 16oz por kilo",
    desc: "Base Crystal para bebidas base agua. Ideal para bebidas de autor refrescantes sin lactosa.",
    tags: ["Base agua", "22 frappés/kg", "Sin lactosa"],
  },
  {
    id: 10,
    name: "Icy Frutz 1kg",
    cat: "bases",
    image: "assets/productos/icy-frutz.webp",
    emoji: "🧊",
    price: 260,
    badge: null,
    stock: 16,
    flavors: "Chamoyada de Mango · Chamoyada de Fresa · Fresa · Mango · Blueberry · Cereza",
    desc: "Base en polvo para preparar bebidas frías tipo granizada y smoothie helado suave.",
    tags: ["1 Kilo", "Smoothie", "Helado suave"],
  },

  // ─── BUBBAS & TAPIOCA ────────────────────────────────────
  {
    id: 11,
    name: "Bubbas Neón",
    cat: "bubbas",
    image: "assets/productos/bubbas-neon.webp",
    emoji: "🫧",
    price: 240,
    badge: "hot",
    stock: 20,
    flavors: "Moras · Citrus · Manzana Verde · Algodón de Azúcar · Uva · Mango",
    desc: "Perlas Bubbas con colores neón fluorescentes. Ideales para bubble tea y bebidas llamativas.",
    tags: ["Neón", "Bubbas", "Verona"],
  },
  {
    id: 12,
    name: "Bubbas Frutales",
    cat: "bubbas",
    image: "assets/productos/bubbas-frutales.webp",
    emoji: "🍇",
    price: 240,
    badge: null,
    stock: 18,
    flavors: "Fresa · Chamoy · Frutos Rojos · Cereza · Kiwi · Taro · Maracuyá",
    desc: "Perlas explosivas frutales rellenas de jarabe. Perfectas para bubble tea, nieves y helados.",
    tags: ["Frutales", "Contentti", "1 Kilo"],
  },
  {
    id: 13,
    name: "Pastas Escarcha 1.1kg",
    cat: "bubbas",
    image: "assets/productos/pasta-escarcha-1kg.webp",
    emoji: "🍯",
    price: 95,
    badge: null,
    stock: 30,
    flavors: "Sandía Chamoy · Sandía Pop · Mango Chamoy · Fresa Chamoy · Tamarindo de Peluche · Mora Pop",
    desc: "Pasta escarcha escarchadora para vasos de micheladas y bebidas. Marca FrutiMich.",
    tags: ["1.1 Kilo", "Escarcha", "FrutiMich"],
  },
  {
    id: 14,
    name: "Pasta Escarcha 5kg",
    cat: "bubbas",
    image: "assets/productos/pasta-escarcha-5kg.webp",
    emoji: "🪣",
    price: 390,
    badge: null,
    stock: 8,
    flavors: "Tamarindo de Peluche · Chamoy Tradicional",
    desc: "Presentación mayoreo de pasta escarcha. Ideal para negocios con alto volumen de producción.",
    tags: ["5 Kilos", "Mayoreo", "Escarcha"],
  },
  {
    id: 15,
    name: "Tapioca Negra 1kg",
    cat: "bubbas",
    image: "assets/productos/tapioca-negra.webp",
    emoji: "🧋",
    price: 185,
    badge: null,
    stock: 22,
    flavors: "Perlas de tapioca negra para bubble tea",
    desc: "Perlas de tapioca negra de alta calidad. Cocer y servir en bubble tea o bebidas frías.",
    tags: ["1 Kilo", "Tapioca", "Bubble Tea"],
  },
  {
    id: 16,
    name: "Tapioca Crystal 2kg",
    cat: "bubbas",
    image: "assets/productos/tapioca-crystal.webp",
    emoji: "🫙",
    price: 350,
    badge: null,
    stock: 10,
    flavors: "Azúcar morena — tapioca lista",
    desc: "Tapioca Crystal con azúcar morena. Presentación 2 kilos. Lista para usar más rápido.",
    tags: ["2 Kilos", "Crystal", "Morena"],
  },

  // ─── VASOS & DESECHABLES ─────────────────────────────────
  {
    id: 17,
    name: "Vasos Café 16oz (50pzas)",
    cat: "desechables",
    image: "assets/productos/vasos-cafe-16oz.webp",
    emoji: "☕",
    price: 100,
    badge: null,
    stock: 35,
    flavors: "16 oz · 50 piezas por paquete",
    desc: "Vasos para bebida caliente. También en 12oz ($89). Ideales para café, té y lattes.",
    tags: ["50 piezas", "16 oz", "Bebida caliente"],
  },
  {
    id: 18,
    name: "Vasos Frappé 50pzas",
    cat: "desechables",
    image: "assets/productos/vasos-frappe.webp",
    emoji: "🥤",
    price: 68,
    badge: null,
    stock: 28,
    flavors: "12 oz ($68) · 14 oz ($72) · 16 oz ($79)",
    desc: "Vasos plásticos para frappé y sodas italianas. Transparentes y resistentes. Varios tamaños.",
    tags: ["50 piezas", "Transparente", "Frappé"],
  },
  {
    id: 19,
    name: "Vasos + Tapa Boquilla 100u",
    cat: "desechables",
    image: "assets/productos/vasos-tapa-boquilla.webp",
    emoji: "🧃",
    price: 350,
    badge: "sale",
    stock: 15,
    flavors: "100 vasos + 100 tapas boquilla · 12 oz y 16 oz",
    desc: "Set completo de 100 vasos plásticos con 100 tapas de boquilla. Transparentes y resistentes.",
    tags: ["100 piezas", "Tapa incluida", "12/16 oz"],
  },
  {
    id: 20,
    name: "Tapa Domo (50pzas)",
    cat: "desechables",
    image: "assets/productos/tapa-domo.webp",
    emoji: "🔵",
    price: 40,
    badge: null,
    stock: 40,
    flavors: "Tapa domo ($40) · Tapa plana con ranadura ($35)",
    desc: "Tapas para vasos de frappé. Domo $40 y plana con ranadura $35. 50 piezas.",
    tags: ["50 piezas", "Tapa domo", "Plástico"],
  },
  {
    id: 21,
    name: "Popotes Neón 30pzas",
    cat: "desechables",
    image: "assets/productos/popotes-neon.webp",
    emoji: "🌈",
    price: 30,
    badge: null,
    stock: 50,
    flavors: "Bolsa de un color con 30 popotes · Colores neón y negro",
    desc: "Popotes anchos de colores neón para bubble tea y bubbas. También negros para tapioca.",
    tags: ["30 piezas", "Neón", "Tapioca/Bubbas"],
  },
  {
    id: 22,
    name: "Banderillas Tajín 50pzas",
    cat: "desechables",
    image: "assets/productos/banderillas-tajin.webp",
    emoji: "🌶️",
    price: 115,
    badge: null,
    stock: 25,
    flavors: "Tajín ($115) · Mora Azul ($125)",
    desc: "Banderillas decorativas para vasos de michelada. MicheMega. 50 piezas por paquete.",
    tags: ["50 piezas", "MicheMega", "Micheladas"],
  },

  // ─── UTENSILIOS BAR ──────────────────────────────────────
  {
    id: 23,
    name: "Coctelera Premium 500ml",
    cat: "utensilios",
    image: "assets/productos/coctelera-premium.png",
    emoji: "🍸",
    price: 130,
    badge: "new",
    stock: 12,
    flavors: "Acero inoxidable plata · 500ml",
    desc: "Coctelera de lujo 3 piezas. Acero inoxidable de alta resistencia, tapa hermética.",
    tags: ["Acero inox", "500 ml", "Premium"],
  },
  {
    id: 24,
    name: "Vaso Shaker 28oz",
    cat: "utensilios",
    image: "assets/productos/vaso-shaker.png",
    emoji: "🥃",
    price: 135,
    badge: null,
    stock: 10,
    flavors: "Acero inoxidable · 28 oz",
    desc: "Vaso shaker estilo Boston de acero inoxidable. Ideal para coctelería profesional.",
    tags: ["Acero inox", "28 oz", "Boston style"],
  },
  {
    id: 25,
    name: "Jigger Japonés 30/60ml",
    cat: "utensilios",
    image: "assets/productos/jigger-japones.png",
    emoji: "⚖️",
    price: 220,
    badge: "hot",
    stock: 8,
    flavors: "Negro 30/60ml ($220) · Dorado 30/60ml ($250)",
    desc: "Jigger medidor tipo japonés de precisión. Acero inoxidable negro o dorado.",
    tags: ["30/60 ml", "Japonés", "Acero inox"],
  },
  {
    id: 26,
    name: "Escarchador 3 Compartimentos",
    cat: "utensilios",
    image: "assets/productos/escarchador-3-compartimientos.png",
    emoji: "🟰",
    price: 270,
    badge: null,
    stock: 9,
    flavors: "Plástico negro premium · 16 x 7.5 cm",
    desc: "Escarchador profesional de 3 compartimentos. Sal, azúcar y escarcha simultáneamente.",
    tags: ["3 compartimentos", "16x7.5cm", "Pro"],
  },
  {
    id: 27,
    name: "Tapete Escurridor Bar",
    cat: "utensilios",
    image: "assets/productos/tapete-escurridor-bar.png",
    emoji: "🟫",
    price: 195,
    badge: null,
    stock: 14,
    flavors: "45x31cm ($195) · Angosto 59.5x8cm ($120)",
    desc: "Tapete escurridor de plástico negro premium para barra de bar y cafetería.",
    tags: ["45x31 cm", "Negro", "Bar Premium"],
  },
  {
    id: 28,
    name: "Macerador Acero Inox",
    cat: "utensilios",
    image: "assets/productos/macerador-acero.png",
    emoji: "🔨",
    price: 185,
    badge: null,
    stock: 11,
    flavors: "Acero inoxidable plata · 20cm · 87gr",
    desc: "Macerador profesional de acero inoxidable. Alta resistencia para frutas y hierbas.",
    tags: ["Acero inox", "20 cm", "87 gr"],
  },
  {
    id: 29,
    name: "Cubeta para hielo de acero inoxidable 1.2 L",
    cat: "utensilios",
    image: "assets/productos/cubeta-hielo.png",
    emoji: "🍸",
    price: 79,
    badge: "new",
    stock: 12,
    flavors: "Acero inoxidable plata · 1.2 L · Uso profesional",
    desc: "Cubeta para hielo de acero inoxidable con diseño elegante y profesional. Ideal para mantener el hielo frío por más tiempo en bares, restaurantes o eventos.",
    tags: ["Acero inox", "1.2 L", "Premium"],
  },
  {
    id: 30,
    name: "Hielera de acero inoxidable para botellas 4.5 L",
    cat: "utensilios",
    image: "assets/productos/hielera-botellas-4L.png",
    emoji: "🍸",
    price: 130,
    badge: "new",
    stock: 12,
    flavors: "Acero inoxidable plata · 4.5 L · Para botellas",
    desc: "Hielera de acero inoxidable diseñada para enfriar botellas de manera eficiente. Capacidad 4.5 litros, ideal para vinos, cervezas o bebidas en bares y eventos.",
    tags: ["Acero inox", "4.5 L", "Botellas", "Premium"],
  },
  {
    id: 31,
    name: "Destapador de botellas",
    cat: "utensilios",
    image: "assets/productos/destapador-botellas.png",
    emoji: "🍾",
    price: 45,
    badge: null,
    stock: 11,
    flavors: "Acero inoxidable plata · 18cm · uso profesional",
    desc: "Destapador de botellas plano de acero inoxidable. Diseño práctico y resistente, ideal para uso profesional en bares y restaurantes.",
    tags: ["Acero inox", "18 cm", "Plano", "Premium"],
  },
  {
    id: 32,
    name: "Colador fino",
    cat: "utensilios",
    image: "assets/productos/colador-fino.png",
    emoji: "🔩",
    price: 82,
    badge: null,
    stock: 11,
    flavors: "Acero inoxidable plata · 22cm · colador fino",
    desc: "Colador fino de acero inoxidable para filtrar líquidos con precisión. Ideal para coctelería profesional.",
    tags: ["Acero inox", "22 cm", "Colador fino", "Coctelería", "Premium"],
  },
  {
    id: 33,
    name: "Colador oruga",
    cat: "utensilios",
    image: "assets/productos/colador-oruga.png",
    emoji: "🌀",
    price: 48,
    badge: null,
    stock: 11,
    flavors: "Acero inoxidable plata · 12x15x2.5 cm · colador oruga",
    desc: "Colador tipo oruga de acero inoxidable. Retiene hielo y sólidos para una presentación limpia en barra.",
    tags: ["Acero inox", "12x15x2.5 cm", "Colador oruga", "Coctelería", "Premium"],
  },
  {
    id: 34,
    name: "Macerador Polipropileno",
    cat: "utensilios",
    image: "assets/productos/macerador-polipropileno.webp",
    emoji: "🔨",
    price: 45,
    badge: null,
    stock: 11,
    flavors: "Polipropileno · 21cm · Macerador · Uso profesional",
    desc: "Macerador de polipropileno para triturar frutas, hierbas y otros ingredientes. Ligero y resistente.",
    tags: ["Polipropileno", "21 cm", "Macerador", "Premium"],
  },
  {
    id: 35,
    name: "Cuchara para hielo aluminio",
    cat: "utensilios",
    image: "assets/productos/cuchara-para-hielo-aluminio.png",
    emoji: "🥄",
    price: 75,
    badge: null,
    stock: 11,
    flavors: "Aluminio · 5 oz (147ml) · Uso profesional",
    desc: "Cuchara para hielo de aluminio. Ligera y resistente, ideal para coctelería y bares.",
    tags: ["Aluminio", "Hielo", "Cuchara", "Premium"],
  },
];

const CATEGORIES = [
  { id: "esencias",    label: "Esencias & Siropes",  emoji: "🍶", color: "pink",   desc: "Verona · Torino · más" },
  { id: "bases",       label: "Bases en Polvo",       emoji: "☕", color: "cyan",   desc: "Frappé · Latte · Café" },
  { id: "bubbas",      label: "Bubbas & Tapioca",     emoji: "🫧", color: "gold",   desc: "Neón · Frutales · Crystal" },
  { id: "desechables", label: "Vasos & Desechables",  emoji: "🥤", color: "purple", desc: "12, 14, 16 oz · tapas" },
  { id: "utensilios",  label: "Utensilios Bar",       emoji: "🍸", color: "green",  desc: "Cocteleras · jiggers" },
];
